### ISSUE TITLE
Difference between this and SimpleWebsocketServer?

### ISSUE THREAD

**Issue by subnut** [pikhovkin/simple-websocket-server#3]
The README says that this is _based_ on [dpallot/simple-websocket-server](https://github.com/dpallot/simple-websocket-server), but I couldn't find any obvious difference between this package and dpallot's one

Could you please clarify the main differences?

**Comment by subnut** [comment]
Ping @pikhovkin

**Comment by pikhovkin** [comment]
@subnut 
- Pythonic way
- API compatibility with classes in built-in `http.server` module
- Improved tests
- Connected CI

also this package was added on pypi before parent package added on pypi

**Comment by subnut** [comment]
@pikhovkin 
Thanks for the clarification :+1: 

> - Pythonic way

It would be better if you could explain this point a little more :sweat_smile: 

---
Issue can be closed
