### ISSUE TITLE
Fix your library lol

### ISSUE THREAD

**Issue by ghost** [pikhovkin/simple-websocket-server#9]
Functionality works on, Mac OS and Linux.

Server does not run on Windows at all.

This had been tested with and without admin perms and on ports <1024 and >1024

I confirmed this is what is breaking it by testing alternative librarys

I could try and use those library's but this is the most easy to use so I'd rather not have to port my entire program already

So just fix this library please, if u need someone to help test I'll be more than happy to do that

**Comment by pikhovkin** [comment]
Sure, welcome to pull requests

**Comment by Footsiefat** [comment]
Can't you fix it since you're actually familiar with this library since you made it? I was just offering to test any patches you made FYI if you don't have a windows PC.

**Comment by ghost** [comment]
What the heck lol, I tested it on a VM and works okay. Although FYI it doesn't seem to work if you leave the IP address blank so you have to set it to 127.0.0.1

**Comment by junhaoliao** [comment]
https://github.com/dpallot/simple-websocket-server/pull/103

I have it fixed on my branch(https://github.com/junhaoliao/simple-websocket-server). Unfortunately, it seems the original author is not actively maintaining the original repo, so my pull request has been there for almost a year but it doesn't get merged. 

This current repo is not forked from the original repo, so I am not able to submit a pull request here either. 

To install my branch, you can add this to your requirements.txt:
```
git+https://github.com/junhaoliao/simple-websocket-server#egg=SimpleWebSocketServer
```

**Comment by pikhovkin** [comment]
@Footsiefat @junhaoliao I simply added
```python
...
if not host:
    host = '127.0.0.1'
...
```
Try new [release 0.4.2](https://pypi.org/project/simple-websocket-server/)

**Comment by ghost** [comment]
Thanks heaps, can't really test it currently due to me only using Linux now but appreciate the patch
